from enum import Enum

class UserState(str, Enum):
    NEW = "NEW"
    ACCOUNT_CREATED = "ACCOUNT_CREATED"
    FULL_SYNC_RUNNING = "FULL_SYNC_RUNNING"
    FULL_SYNC_DONE = "FULL_SYNC_DONE"
    DELTA_SYNC_RUNNING = "DELTA_SYNC_RUNNING"
    DELTA_PENDING = "DELTA_PENDING"
    DELTA_DONE = "DELTA_DONE"
    ERROR = "ERROR"
